### ISSUE TITLE
Preventing Mining Drops?

### ISSUE THREAD

**Issue by urcousinclaire** [Christofmeg/BrutalHarvest#20]
When mining with an iron pickaxe, you cannot get drops for copper and iron. Wondering if this is an addition to the mod or just a bug?

**Comment by Christofmeg** [comment]
That is not a feature of this mod. I'll need to know this:

* Forge version
* Brutal Harvest version
* Modlist and version of those mods

**Comment by urcousinclaire** [comment]
- Forge version is 1.20.1
- BH version 1.11.0
- Modlist and Versions as Follows:
Botany Pots 13.0.39
Botany Trees 9.0.17
Carry On 2.1.2.7
Alex's Mobs 1.22.9
Diet 2.1.1+1.20.1
Farmer's Delight 1.20.1 - 1.2.4
Enhanced Farming 2.1.1

Thanks! :)

**Comment by Christofmeg** [comment]
Forge 1.20.1 - 47.3.0

![image](https://github.com/user-attachments/assets/0178b41e-956d-401a-8bc9-cf5f52fa5b2e)
I'm unable to reproduce your issue with default settings.

Do you have any other mods/datapacks/plugins or some special config that might be causing it?

**Comment by Christofmeg** [comment]
Closing case due to inactivity and me not being able to reproduce the issue with provided information.
